export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const VERIFY_AUTH_REQUEST = 'VERIFY_AUTH_REQUEST';
export const VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';
export const VERIFY_AUTH_FAILURE = 'VERIFY_AUTH_FAILURE';

export const SET_PLANN = 'SET_PLANN';
export const FILTER_PLAN = 'FILTER_PLAN';
export const SET_ALL_PLANS = 'SET_ALL_PLANS';

export const SET_USER = 'SET_USER';

export const LOGOUT = 'LOGOUT';
